openapi: 3.0.1
info:
  title: User microservice of library management system
  description: User microservice of library management system that provides operations with user
  version: 1.0.0
servers:
  - url: "http://localhost:8080"
tags:
  - name: User
components:
  schemas:
    UserDTO:
      title: "An user"
      description: "User object providing information about user"
      properties:
        username: {type: string, description: "Username of user", example: "xholub"}
        address: {type: string, description: "Address of user", example: "Bratislavská 850/11"}
        userType: {type: string, description: "Type of user in library", enum: ["Member", "Librarian"], example: "Member"}
        birthDate: {type: string, format: date, description: "Date of birth of user", example: "2003-06-25" }
paths:
  /api/users:
    get:
      tags:
        - User
      summary: Returns all users
      operationId: getUsers
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                title: UsersResponse
                items:
                  $ref: '#/components/schemas/UserDTO'
