image: jelastic/maven:3.9.5-openjdk-21
stages:
  - build
  - test

build:
  tags:
    - shared-fi
  stage: build
  script:
    - mvn package -DskipTests=true

test:
  tags:
    - shared-fi
  stage: test
  script:
    - mvn verify
