version: '3.8'
services:
  rental:
    build:
      context: ./rental
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
  reservation:
    build:
      context: ./reservation/
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
  user:
    build:
      context: ./user/
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
  book:
    build:
      context: ./book
      dockerfile: Dockerfile
    ports:
      - "8083:8083"

