{
 "title": "Library Management System Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Other",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true
  },
  {
   "title": "Scrape Duration",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "topk(5, max(scrape_duration_seconds) by (job))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Query Durations",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "prometheus_engine_query_duration_seconds{job=\"prometheus\", quantile=\"0.99\"}",
     "legendFormat": "{{slice}}_p99"
    }
   ]
  },
  {
   "title": "Statistics across services",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true
  },
  {
   "title": "Comparative view of HTTP requests load on all services",
   "type": "timeseries",
   "description": "Comparative view of HTTP requests load on all services",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(hikaricp_connections_acquire_seconds_count[$__rate_interval])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  { "title": "HTTP requests by service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Book service HTTP requests",
   "type": "piechart",
   "description": "HTTP requests to book service by endpoint and type",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_server_requests_seconds_count{job=\"book-service\", uri=~\"/api/books/{id}|/api/books|/api/books/{id}/borrowings\"}",
     "legendFormat": "{{method}}{{uri}}"
    }
   ]
  },
  {
   "title": "User service HTTP requests",
   "type": "piechart",
   "description": "HTTP requests to user service by endpoint and type",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_server_requests_seconds_count{job=\"user-service\", uri=~\"/api/users/{id}|/api/users|/api/users/adults\"}",
     "legendFormat": "{{method}} {{uri}}"
    }
   ]
  },
  {
   "title": "Borrowing service HTTP requests",
   "type": "piechart",
   "description": "HTTP requests to borrowing service by endpoint and type",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_server_requests_seconds_count{job=\"borrowing-service\", uri=~\"/api/borrowings/{id}|/api/borrowings|/api/activeBorrowings|/api/borrowings/{id}/fine\"}",
     "legendFormat": "{{method}} {{uri}}"
    }
   ]
  },
  {
   "title": "Reservation service HTTP requests",
   "type": "piechart",
   "description": "HTTP requests to reservation service by endpoint and type",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_server_requests_seconds_count{job=\"reservation-service\", uri=~\"/api/reservations/{id}|/api/reservations|/api/reservations/expired|/api/reservations/active\"}",
     "legendFormat": "{{method}} {{uri}}"
    }
   ]
  }
 ]
}