global:
  scrape_interval: 1s
  external_labels:
    monitor: 'my-monitor'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: [ 'localhost:9090' ]
  - job_name: 'borrowing-service'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: [ 'borrowing:8080' ]
  - job_name: 'reservation-service'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: [ 'reservation:8081' ]
  - job_name: 'user-service'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: [ 'user:8082' ]
  - job_name: 'book-service'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: [ 'book:8083' ]
