global:
  scrape_interval: 1s
  external_labels:
    monitor: 'my-monitor'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: [ 'localhost:9090' ]
  - job_name: 'user'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: [ 'localhost:8082', # user service
                   'localhost:8081', # reservation service
      ]

