openapi: 3.0.1
info:
  title: Rental microservice of library management system
  description: Rental microservice of library management system that provides operations on rentals
  version: 1.0.0
servers:
  - url: "http://localhost:8081"
tags:
  - name: Rental

components:
  schemas:
    Rental:
      title: "A rental"
      description: "Represents a single rental of a book in a library"
      properties:
        book:
          type: string
          description: "Title of the book being rented"
          example: "The Lords of the Rings: The Two Towers"
        rentedBy:
          type: string
          description: "Name of the person renting the book"
          example: "Franta Vopršálek"
        borrowDate:
          type: string
          format: date-time
          description: "Date when the book was borrowed"
          example: "2024-04-03T10:15:30Z"

paths:
  /api/test:
    get:
      tags:
        - Rental
      summary: Returns test message response
      operationId: test
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                title: RentalTestResponse
                properties:
                  message:
                    type: string