openapi: 3.0.1
info:
  title: Rental microservice of library management system
  description: Rental microservice of library management system that provides operations on rentals
  version: 1.0.0
servers:
  - url: "http://localhost:8081"
tags:
  - name: Rental

components:
  schemas:
    Rental:
      title: "A rental"
      description: "Represents a single rental of a book in a library"
      properties:
        book:
          type: string
          description: "Title of the book being rented"
          example: "The Lord of the Rings: The Two Towers"
        rentedBy:
          type: string
          description: "Name of the person renting the book"
          example: "Franta Vopršálek"
        borrowDate:
          type: string
          format: date-time
          description: "Date when the book was borrowed"
          example: "2024-04-03T10:15:30Z"
        expectedReturnDate:
          type: string
          format: date-time
          description: "Date when the book is expected to be returned"
          example: "2024-07-03T10:15:30Z"
        returned:
          type: boolean
          description: "Indicates whether the book has been returned"
          example: false
        returnDate:
          type: string
          format: date-time
          description: "Date when the book was returned, null If it hasn't been returned yet"
          example: "2024-04-06T08:30:00Z"
        lateReturnWeeklyFine:
          type: number
          format: big decimal
          description: "Weekly fine for late returns in euros"
          example: "1.50"

paths:
  /api/test:
    get:
      tags:
        - Rental
      summary: Returns test message response
      operationId: test
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                title: RentalTestResponse
                properties:
                  message:
                    type: string
  /api/rentals:
    get:
      tags:
        - Rental
      summary: Returns all rentals
      operationId: getRentals
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                title: RentalsResponse
                items:
                  $ref: '#/components/schemas/Rental'
    post:
      tags:
        - Rental
      summary: Creates new rental
      operationId: createRental
      parameters:
        - { name: book, in: query, required: true, schema: { type: string }, description: "Title of book" }
        - { name: rentedBy, in: query, required: true, schema: { type: string }, description: "Name of renter" }
        - { name: borrowDate, in: query, required: true, schema: { type: string, format: date-time }, description: "Borrow date" }
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Rental'
  /api/rentals/{id}:
    get:
      tags:
        - Rental
      summary: Get rental by id
      operationId: getRental
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Rental'
    patch:
      tags:
        - Rental
      summary: Update an existing rental
      operationId: updateRental
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
            format: int64
        - in: query
          name: book
          required: false
          schema:
            type: string
        - in: query
          name: rentedBy
          required: false
          schema:
            type: string
        - in: query
          name: borrowDate
          required: false
          schema:
            type: string
            format: date-time
        - in: query
          name: expectedReturnDate
          required: false
          schema:
            type: string
            format: date-time
        - in: query
          name: returned
          required: false
          schema:
            type: boolean
        - in: query
          name: returnDate
          required: false
          schema:
            type: string
            format: date-time
        - in: query
          name: lateReturnWeeklyFine
          required: false
          schema:
            type: number
            format: big decimal
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Rental'
        '404':
          description: Not found
    delete:
      tags:
        - Rental
      summary: Delete rental by id
      operationId: deleteRental
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Successfully deleted
        '204':
          description: Failed to delete or couldn't find the rental
        '404':
          description: No such rental
  /api/rentals/{id}/fine:
    get:
      tags:
        - Rental
      summary: Get fine for a rental by ID
      operationId: getFineById
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: number
                format: big decimal
        '404':
          description: Not found
