openapi: 3.0.1
info:
  title: Reservation microservice of library management system
  description: Reservation microservice of library management system that provides operations on reservations
  version: 1.0.0
servers:
  - url: "http://localhost:8081"
tags:
  - name: Reservation

components:
  securitySchemes:
    MUNI:
      type: oauth2
      description: get access token with OAuth 2 Authorization Code Grant
      flows:
        authorizationCode:
          authorizationUrl: https://oidc.muni.cz/oidc/authorize
          tokenUrl: https://oidc.muni.cz/oidc/token
          scopes:
            test_read: Used for reading data
            test_write: Used for modifying data
            test_1: Used for deleting data

  schemas:
    ReservationDTO:
      title: "A reservation"
      description: "Reservation object"
      properties:
        id: { type: integer, format: int64, description: "Id of reservation", example: 23 }
        bookId: { type: integer, format: int64, description: "Id of book that is part of the reservation", example: 11 }
        reserveeId: { type: integer, format: int64, description: "Id of user that created this reservation", example: 11 }
        reservedFrom: { type: string, format: date-time, description: "Date when reservation was created", example: "2024-04-03T10:15:30Z" }
        reservedTo: { type: string, format: date-time, description: "Date when the reservation was/will be cancelled", example: "2024-04-03T10:15:30Z" }

paths:
  /api/reservations:
    get:
      tags:
        - Reservation
      summary: Returns all reservations
      operationId: getReservations
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ReservationDTO'
      security:
        - MUNI: [ test_read ]

    post:
      tags:
        - Reservation
      summary: Creates new reservation
      operationId: createReservation
      parameters:
        - { name: bookId,
            in: query,
            required: true,
            schema: { type: integer, format: int64 },
            description: "Id of reserved book" }
        - { name: reserveeId,
            in: query,
            required: true,
            schema: { type: integer, format: int64 },
            description: "Id of user reserving the book" }
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReservationDTO'
      security:
        - MUNI: [ test_write ]

    delete:
      tags:
        - Reservation
      summary: Delete all reservations
      operationId: deleteReservations
      responses:
        '204':
          description: No content
      security:
        - MUNI: [ test_1 ]

  /api/reservations/{id}:
    get:
      tags:
        - Reservation
      summary: Get reservation by id
      operationId: getReservation
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReservationDTO'
      security:
        - MUNI: [ test_read ]

    patch:
      tags:
        - Reservation
      summary: Update an existing reservation
      operationId: updateReservation
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
            format: int64
        - in: query
          name: bookId
          required: false
          schema:
            type: integer
            format: int64
        - in: query
          name: reserveeId
          required: false
          schema:
            type: integer
            format: int64
        - in: query
          name: reservedFrom
          required: false
          schema:
            type: string
            format: date-time
          description: "For example: 2023-05-21T14:30:00+01:00"
        - in: query
          name: reservedTo
          required: false
          schema:
            type: string
            format: date-time
          description: "For example: 2023-05-21T14:30:00+01:00"
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReservationDTO'
        '404':
          description: Not found
      security:
        - MUNI: [ test_write ]

    delete:
      tags:
        - Reservation
      summary: Delete reservation by id
      operationId: deleteReservation
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '204':
          description: No content
      security:
        - MUNI: [ test_1 ]

  /api/reservations/active:
    get:
      tags:
        - Reservation
      summary: Returns all active reservations
      operationId: getActiveReservations
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ReservationDTO'
      security:
        - MUNI: [ test_read ]

  /api/reservations/expired:
    get:
      tags:
        - Reservation
      summary: Returns all expired reservations
      operationId: getExpiredReservations
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ReservationDTO'
      security:
        - MUNI: [ test_read ]
