openapi: 3.0.1
info:
  title: Reservation microservice of library management system
  description: Reservation microservice of library management system that provides operations on reservations
  version: 1.0.0
servers:
  - url: "http://localhost:8084"
tags:
  - name: Reservation
paths: {}

