openapi: 3.0.1
info:
  title: Book microservice of library management system
  description: Book microservice of library management system that provides operations on books
  version: 1.0.0
servers:
  - url: "http://localhost:8080"
tags:
  - name: Book

components:
  schemas:
    Book:
      title: "A book"
      description: "Book object"
      properties:
        title: {type: string, description: "Book title / name", example: "Java tutorial"}
        description: {type: string, description: "Description of the book", example: "It is *** hard"}
        author: {type: string, description: "Author name", example: "Bruno Rossi"}
        status: {type: string, description: "Status of the book", enum: ["Available", "Reserved", "Rented"], example: "Reserved" }

paths:
  /api/test:
    get:
      tags:
        - Book
      summary: Returns test message response
      operationId: test
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                title: BookTestResponse
                properties:
                  message:
                    type: string

  /api/books:
    get:
      tags:
        - Book
      summary: Returns all books
      operationId: getBooks
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                title: BooksResponse
                items:
                  $ref: '#/components/schemas/Book'
