openapi: 3.0.1
info:
  title: Book microservice of library management system
  description: Book microservice of library management system that provides operations on books
  version: 1.0.0
servers:
  - url: "http://localhost:8080"
tags:
  - name: Book

components:
  schemas:
    BookStatus:
      type: string
      enum:
        - Available
        - Reserved
        - Rented
    Book:
      title: "A book"
      description: "Book object"
      properties:
        title: {type: string, description: "Book title / name", example: "Java tutorial"}
        description: {type: string, description: "Description of the book", example: "It is *** hard"}
        author: {type: string, description: "Author name", example: "Bruno Rossi"}
        status:
          $ref: '#/components/schemas/BookStatus'

paths:
  /api/test:
    get:
      tags:
        - Book
      summary: Returns test message response
      operationId: test
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                title: BookTestResponse
                properties:
                  message:
                    type: string

  /api/books:
    get:
      tags:
        - Book
      summary: Returns all books
      operationId: getBooks
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                title: BooksResponse
                items:
                  $ref: '#/components/schemas/Book'
    post:
      tags:
        - Book
      summary: Creates new book
      operationId: createBook
      parameters:
        - { name: title, in: query, required: true, schema: { type: string }, description: "Title of book" }
        - { name: description, in: query, required: true, schema: { type: string }, description: "Description of book" }
        - { name: author, in: query, required: true, schema: { type: string }, description: "Author of book" }
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Book'
