@startuml

class Book {
String title
String author
String description
BookStatus status
}

class User {
String name
UserType type
}

class Reservation {
Book book
User reservedBy
Date reservedUntil
}

class Rental {
Book book
User rentedBy
Date borrowDate
Date returnDate
}

enum UserType {
LIBRARIAN
MEMBER
}

enum BookStatus {
RESERVED
RENTED
AVAILABLE
}

Book -- BookStatus
User -- UserType


@enduml