@startuml

left to right direction

actor Librarian
actor Member
actor Anonymous
actor User
actor "Registered user"

"Registered user" <|.. Librarian
"Registered user" <|.. Member
User <|.. "Registered user"
User <|.. Anonymous

rectangle "Library Management System" {

  usecase "List reservations"
  usecase "Reserve book"
  usecase "Show reservation details"
  usecase "Update reservation details"
  usecase "Remove reservation"

  usecase "List accounts"
  usecase "Create account"
  usecase "Show account details"
  usecase "Update account details"
  usecase "Delete account"
  usecase "Manage accounts"

  usecase "List books"
  usecase "Create book"
  usecase "Show book details"
  usecase "Update book details"
  usecase "Remove book"

  usecase "List borrowings"
  usecase "Borrow book"
  usecase "Show borrowing details"
  usecase "Update borrowing details"
  usecase "Remove borrowing"

  usecase "Configure fine"


}

Anonymous --> "Create account"

User --> "List books"
User --> "Show book details"

Librarian --> "Update reservation details"
Librarian --> "Remove reservation"
Librarian --> "List accounts"
Librarian --> "Create account"
Librarian --> "Manage accounts"
Librarian --> "Create book"
Librarian --> "Remove book"
Librarian --> "Update book details"
Librarian --> "Configure fine"
Librarian --> "Update borrowing details"
Librarian --> "Remove borrowing"

"Registered user" --> "List reservations"
"Registered user" --> "Reserve book"
"Registered user" --> "Show reservation details"
"Registered user" --> "Show account details"
"Registered user" --> "Update account details"
"Registered user" --> "Delete account"
"Registered user" --> "List borrowings"
"Registered user" --> "Borrow book"
"Registered user" --> "Show borrowing details"


@enduml