@startuml

left to right direction

actor Librarian
actor Member
actor Anonymous
actor User
actor "Registered user"

"Registered user" <|.. Librarian
"Registered user" <|.. Member
User <|.. "Registered user"
User <|.. Anonymous

rectangle "Library Management System" {
  usecase "Add book"
  usecase "Remove book"
  usecase "Update book"

  usecase "Search books"
  usecase "Display book detail"

  usecase "Reserve book"
  usecase "Borrow book"
  usecase "Return book"

  usecase "Show borrowed books"
  usecase "Show fines"

  usecase "Manage account"
  usecase "Manage accounts"

  usecase "Configure fine"
  usecase "Update Member fine status"

  usecase "Create account"
}

Anonymous --> "Create account"

User --> "Search books"
User --> "Display book detail"

Librarian --> "Add book"
Librarian --> "Remove book"
Librarian --> "Update book"
Librarian --> "Manage accounts"
Librarian --> "Configure fine"
Librarian --> "Update Member fine status"

"Registered user" --> "Reserve book"
"Registered user" --> "Borrow book"
"Registered user" --> "Return book"
"Registered user" --> "Show borrowed books"
"Registered user" --> "Show fines"
"Registered user" --> "Manage account"

@enduml